#!/usr/bin/env php
<?php

namespace ASPTest;

require __DIR__ . '/vendor/autoload.php';
include __DIR__ . '/src/database/DBConnect.php';
require __DIR__ . '/src/config/env.php';

use ASPTest\Commands\CreateUserCommand;
use ASPTest\Commands\MigrateDBCommand;
use Symfony\Component\Console\Application;

//$db = new Connect();
define('APP_URL', __DIR__);

$application = new Application();

$application->add(new MigrateDBCommand());
$application->add(new CreateUserCommand());

$application->run();
