version: "3"
services:
  app:
    container_name: asptest-app
    build: .
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    network_mode: "host"

  db:
    container_name: asptest-db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker-compose/mysql:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: asptest-nginx
    restart: unless-stopped
    ports:
      - "90:80"
    volumes:
      - ./docker-compose/nginx:/etc/nginx/conf.d
